version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    working_directory: ~/tst_proj
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo pip install nose coverage; echo $HOME; mkdir test_results; mkdir test_results/all
      - run:
          name: Run Tests
          command: nosetests --with-coverage --with-xunit --xunit-file test_results/all/nosetests.xml --cover-xml --cover-xml-file test_results/all/coverage.xml
      - run:
          name: Coverage Report
          #when: always
          command: coverage html
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results
      - store_artifacts:
          path: htmlcov
      - codecov/upload:
          file: test_results/all/coverage.xml
