version: 2.1
jobs:
  build:
    working_directory: ~/tst_proj
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo pip install nose coverage; echo $HOME; mkdir test_results; mkdir test_results/all; mkdir test_results/coverage
      - run:
          name: Run Tests
          command: nosetests --with-coverage --with-xunit --xunit-file test_results/all/nosetests.xml --cover-xml --cover-xml-file test_results/coverage/coverage.xml
      - run:
          name: Coverage Report
          when: always
          command: coverage html; ls -al test_results; ls -al test_results/coverage
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results
      - store_artifacts:
          path: htmlcov
