version: 2
jobs:
  build:
    working_directory: ~/tst_proj
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo pip install nose coverage; echo $HOME
      - run:
          name: Run Tests
          command: |
            ls
            nosetests --with-coverage
            coverage report
            coverage html
            ls
      - store_artifacts:
          path: htmlcov
