version: 2.1
jobs:
  build-and-test:
    working_directory: ~/tst_proj
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps1.0-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            sudo apt-get install mlocate
            sudo updatedb
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            mkdir test_results
            mkdir test_results/all
            mkdir coverage
      - save_cache:
          key: deps1.0-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            nosetests --with-coverage --with-xunit --xunit-file test_results/all/nosetests.xml --cover-html --cover-html-dir coverage
      - run:
          name: TagIt
          when: always
          command: |
            . venv/bin/activate
            python tag_it.py --uname ${CIRCLE_PROJECT_REPONAME} --key ${GITHUB_TOKEN} --test_file test_results/all/nosetests.xml
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: coverage
workflows:
  version: 2.1
  build_and_test:
      jobs:
        - build-and-test
