version: 2
jobs:
  build:
    working_directory: ~/tst_proj
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo pip install nose coverage; echo $HOME
      - run:
          name: Run Tests
          halt_build_on_fail: false
          command: |
            ls -al
            nosetests --with-coverage
      - run:
          name: Coverage Report
          command: |
            ls -al
            coverage report
            coverage html
            ls -al
      - store_artifacts:
          path: htmlcov
