version: 2
jobs:
  build:
    working_directory: ~/tst_proj
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo pip install nose
      - run: nosetests --with-coverage
